FROM quay.io/orgsync/java:1.8.0_66-b17

ENV FLINK_VERSION 1.1.0
ENV HADOOP_VERSION 27
ENV SCALA_VERSION 2.11
ENV FLINK_HOME /opt/flink
ENV FLINK_DATA /var/flink/

WORKDIR $FLINK_HOME
ENV ARCHIVE_NAME "flink-${FLINK_VERSION}-bin-hadoop${HADOOP_VERSION}-scala_${SCALA_VERSION}.tgz"
RUN curl -O "http://www-us.apache.org/dist/flink/flink-${FLINK_VERSION}/${ARCHIVE_NAME}" \
    && tar --strip-components=1 -zxf $ARCHIVE_NAME \
    && rm $ARCHIVE_NAME \
    && sed -i -e "s/> \"\$out\" 2>&1 < \/dev\/null//g" $FLINK_HOME/bin/flink-daemon.sh \
    && sed -i -e "s/echo \$mypid >> \$pid/echo \$mypid >> \$pid \&\& wait/g" $FLINK_HOME/bin/flink-daemon.sh

COPY entrypoint.sh $FLINK_HOME/bin/

COPY log4j.properties $FLINK_HOME/conf/
COPY log4j.properties $FLINK_HOME/conf/log4j-cli.properties
COPY log4j.properties $FLINK_HOME/conf/log4j-yarn-session.properties

COPY logback.xml $FLINK_HOME/conf/
COPY logback.xml $FLINK_HOME/conf/logback-yarn.xml

ENV PATH $PATH:$FLINK_HOME/bin

VOLUME $FLINK_DATA

EXPOSE 6123
EXPOSE 8081

ENV AKKA_ASK_TIMEOUT=
ENV AKKA_FRAMESIZE=
ENV AKKA_LOG_LIFECYCLE_EVENTS=
ENV AKKA_LOOKUP_TIMEOUT=
ENV AKKA_STARTUP_TIMEOUT=
ENV AKKA_TCP_TIMEOUT=
ENV AKKA_THROUGHPUT=
ENV AKKA_TRANSPORT_HEARTBEAT_INTERVAL=
ENV AKKA_TRANSPORT_HEARTBEAT_PAUSE=
ENV AKKA_TRANSPORT_THRESHOLD=
ENV AKKA_WATCH_HEARTBEAT_INTERVAL=
ENV AKKA_WATCH_HEARTBEAT_PAUSE=
ENV AKKA_WATCH_THRESHOLD=
ENV BLOB_FETCH_BACKLOG=
ENV BLOB_FETCH_NUM_CONCURRENT=
ENV BLOB_FETCH_RETRIES=
ENV BLOB_SERVER_PORT=
ENV BLOB_STORAGE_DIRECTORY=
ENV COMPILER_DELIMITED_INFORMAT_MAX_LINE_SAMPLES=
ENV COMPILER_DELIMITED_INFORMAT_MAX_SAMPLE_LEN=
ENV COMPILER_DELIMITED_INFORMAT_MIN_LINE_SAMPLES=
ENV ENV_JAVA_HOME=$JAVA_HOME
ENV ENV_JAVA_OPTS=
ENV ENV_JAVA_OPTS_JOBMANAGER=
ENV ENV_JAVA_OPTS_TASKMANAGER=
ENV ENV_LOG_DIR=
ENV FS_DEFAULT_SCHEME=file:///
ENV FS_HDFS_HADOOPCONF=
ENV FS_HDFS_HDFSDEFAULT=
ENV FS_HDFS_HDFSSITE=
ENV FS_OUTPUT_ALWAYS_CREATE_DIRECTORY=true
ENV FS_OVERWRITE_FILES=
ENV JOBMANAGER_HEAP_MB=256
ENV JOBMANAGER_RPC_ADDRESS=localhost
ENV JOBMANAGER_RPC_PORT=6123
ENV JOBMANAGER_WEB_BACKPRESSURE_CLEANUP_INTERVAL=
ENV JOBMANAGER_WEB_BACKPRESSURE_DELAY_BETWEEN_SAMPLES=
ENV JOBMANAGER_WEB_BACKPRESSURE_NUM_SAMPLES=
ENV JOBMANAGER_WEB_BACKPRESSURE_REFRESH_INTERVAL=
ENV JOBMANAGER_WEB_CHECKPOINTS_DISABLE=
ENV JOBMANAGER_WEB_CHECKPOINTS_HISTORY=
ENV JOBMANAGER_WEB_HISTORY=
ENV JOBMANAGER_WEB_PORT=8081
ENV JOBMANAGER_WEB_TMPDIR=
ENV JOBMANAGER_WEB_UPLOAD_DIR=$FLINK_DATA/jobs
ENV METRICS_REPORTERS=
ENV METRICS_SCOPE_JM=
ENV METRICS_SCOPE_JM_JOB=
ENV METRICS_SCOPE_TM=
ENV METRICS_SCOPE_TM_JOB=
ENV METRICS_SCOPE_TM_OPERATOR=
ENV METRICS_SCOPE_TM_TASK=
ENV PARALLELISM_DEFAULT=8
ENV RECOVERY_JOB_DELAY=
ENV RECOVERY_MODE=
ENV RECOVERY_ZOOKEEPER_CLIENT_CONNECTION_TIMEOUT=
ENV RECOVERY_ZOOKEEPER_CLIENT_MAX_RETRY_ATTEMPTS=
ENV RECOVERY_ZOOKEEPER_CLIENT_RETRY_WAIT=
ENV RECOVERY_ZOOKEEPER_CLIENT_SESSION_TIMEOUT=
ENV RECOVERY_ZOOKEEPER_PATH_LATCH=
ENV RECOVERY_ZOOKEEPER_PATH_LEADER=
ENV RECOVERY_ZOOKEEPER_PATH_NAMESPACE=
ENV RECOVERY_ZOOKEEPER_PATH_ROOT=
ENV RECOVERY_ZOOKEEPER_QUORUM=
ENV RECOVERY_ZOOKEEPER_STORAGEDIR=$FLINK_DATA/recovery
ENV RESOURCEMANAGER_RPC_PORT=
ENV RESTART_STRATEGY=failure-rate
ENV RESTART_STRATEGY_FAILURE_RATE_DELAY=
ENV RESTART_STRATEGY_FAILURE_RATE_FAILURE_RATE_INTERVAL=
ENV RESTART_STRATEGY_FAILURE_RATE_MAX_FAILURES_PER_INTERVAL=
ENV RESTART_STRATEGY_FIXED_DELAY_ATTEMPTS=
ENV RESTART_STRATEGY_FIXED_DELAY_DELAY=
ENV STATE_BACKEND=filesystem
ENV STATE_BACKEND_FS_CHECKPOINTDIR=$FLINK_DATA/checkpoints
ENV TASK_CANCELLATION_INTERVAL=
ENV TASKMANAGER_DATA_PORT=
ENV TASKMANAGER_DEBUG_MEMORY_LOGINTERVALMS=
ENV TASKMANAGER_DEBUG_MEMORY_STARTLOGTHREAD=
ENV TASKMANAGER_HEAP_MB=512
ENV TASKMANAGER_HOSTNAME=
ENV TASKMANAGER_LOG_PATH=
ENV TASKMANAGER_MEMORY_FRACTION=
ENV TASKMANAGER_MEMORY_OFF_HEAP=
ENV TASKMANAGER_MEMORY_PREALLOCATE=false
ENV TASKMANAGER_MEMORY_SEGMENT_SIZE=
ENV TASKMANAGER_MEMORY_SIZE=
ENV TASKMANAGER_NETWORK_NUMBEROFBUFFERS=
ENV TASKMANAGER_NUMBEROFTASKSLOTS=8
ENV TASKMANAGER_RPC_PORT=
ENV TASKMANAGER_RUNTIME_HASHJOIN_BLOOM_FILTERS=true
ENV TASKMANAGER_RUNTIME_MAX_FAN=
ENV TASKMANAGER_RUNTIME_SORT_SPILLING_THRESHOLD=
ENV TASKMANAGER_TMP_DIRS=
ENV YARN_APPLICATION_ATTEMPTS=
ENV YARN_APPLICATION_MASTER_PORT=
ENV YARN_CONTAINERS_VCORES=
ENV YARN_HEAP_CUTOFF_MIN=
ENV YARN_HEAP_CUTOFF_RATIO=
ENV YARN_HEARTBEAT_DELAY=
ENV YARN_MAXIMUM_FAILED_CONTAINERS=
ENV YARN_PROPERTIES_FILE_LOCATION=

ENTRYPOINT ["entrypoint.sh"]
